# Generated by Django 5.1.1 on 2024-09-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("To_do", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="to_do",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="to_do",
            name="finished_at",
            field=models.DateField(null=True),
        ),
    ]
